//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipCountStat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_stocktake_dbEntities : DbContext
    {
        public siixsem_stocktake_dbEntities()
            : base("name=siixsem_stocktake_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getDetailCount_Result> getDetailCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDetailCount_Result>("getDetailCount");
        }
    
        public virtual ObjectResult<getDetailCountV2_Result> getDetailCountV2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDetailCountV2_Result>("getDetailCountV2");
        }
    
        public virtual ObjectResult<WIP_NOT_QA_VALIDATE_Result> WIP_NOT_QA_VALIDATE(Nullable<int> iDAREA)
        {
            var iDAREAParameter = iDAREA.HasValue ?
                new ObjectParameter("IDAREA", iDAREA) :
                new ObjectParameter("IDAREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WIP_NOT_QA_VALIDATE_Result>("WIP_NOT_QA_VALIDATE", iDAREAParameter);
        }
    }
}
